version: "3.7"
services:
  flask:
    restart: unless-stopped
    volumes:
      - notes:/src/data
    build: .
    ports:
      - "5000:5000"
volumes:
  notes:
#networks:
#  default:
#    external:
#      name: nginxnet
